# exercise 2 :

In [1]:
import numpy as np

In [7]:
A = np.array([range(1,11),range(11,21),range(21,31)])
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [40]:
N = A[:3,:2]
N

array([[ 1,  2],
       [11, 12],
       [21, 22]])

In [14]:
P = A[:3,-3:]
P

array([[ 8,  9, 10],
       [18, 19, 20],
       [28, 29, 30]])

In [39]:
b = A[0:3:2,-4::4]
a = A[0:3:2,2:3:1]
Q = np.concatenate((a,b),axis=1)
Q

array([[ 3,  7],
       [23, 27]])

# exercise 3 :

In [45]:
B = np.array((np.linspace(1,26,9),
              np.linspace(24,72,9)[::-1],
              np.linspace(0,1,9)))
B

array([[ 1.   ,  4.125,  7.25 , 10.375, 13.5  , 16.625, 19.75 , 22.875,
        26.   ],
       [72.   , 66.   , 60.   , 54.   , 48.   , 42.   , 36.   , 30.   ,
        24.   ],
       [ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,
         1.   ]])

# exercise 4 :

In [52]:
from numpy.linalg import *

In [47]:
A = np.array(([1,2,1],[0,1,0],[3,1,2]))
B = np.array(([1,2,3],[1,1,2],[0,1,2]))
C = np.array(([2,1,1],[0,1,1],[4,2,2]))

In [48]:
A + 4*B*C

array([[ 9, 10, 13],
       [ 0,  5,  8],
       [ 3,  9, 18]])

In [49]:
A**3

array([[ 1,  8,  1],
       [ 0,  1,  0],
       [27,  1,  8]], dtype=int32)

In [56]:
print(f"determinant de C egale {det(C)}")

determinant de C egale 0.0


In [54]:
D , V = eig(B)
print(f"les valeurs propres de B : {D}")
print(f"les vecteur propres de B : {V}")

les valeurs propres de B : [-0.37720285  0.72610945  3.65109341]
les vecteur propres de B : [[ 0.44287099  0.71390288  0.7763    ]
 [-0.82644005  0.5508072   0.53918151]
 [ 0.34765231 -0.43238189  0.32656027]]


# exercise 5:

1) resolution de systeme suivant :
6x + y + 5z = 10 |
2x + 2y + 3z = 11 |
4x + 9y + 7z = 12

In [57]:
A = np.array(([6,1,5],[2,2,3],[4,9,7]))
A

array([[6, 1, 5],
       [2, 2, 3],
       [4, 9, 7]])

In [58]:
B = np.array(([10,11,12])).reshape(3,1)
B

array([[10],
       [11],
       [12]])

In [66]:
X = np.linalg.solve(A,B)
try :
    print("les solution de ce systeme est :")
    print(f"X[0] = {X[0]}")
    print(f"X[1] = {X[1]}")
    print(f"X[2] = {X[2]}")
except :
    print("erreur machine singuliere")

les solution de ce systeme est :
X[0] = [-6.8]
X[1] = [-4.2]
X[2] = [11.]


# exercise 6 :

In [71]:
from scipy import *

In [83]:
print("recherche de minimum de la fonction x**2 + 1 en voisinage de V(1):")

recherche de minimum de la fonction x**2 + 1 en voisinage de V(1):


In [89]:
f = lambda x : x*x + 1
x0 = [0.5]
xopt = optimize.minimize(f,x0).x

In [96]:
print(f"minimum en X = {xopt[0]}")

minimum en X = 3.725290242950763e-09
